### ISSUE TITLE
Install rasberry pi OS lite on pi 4

### ISSUE THREAD

**Issue by rkumar2468** [rkumar2468/canakit#1]
Install Rasberry Pi OS on pi 4 (32 bit)
- [x] Download [Lite version from here](https://www.raspberrypi.com/software/operating-systems/)
- [x] Format SD card
- [x] Copy the downloaded image on to the SD card using [balenaEtcher](https://www.balena.io/etcher/)
- [x] Setup/Update configuration for the headless pi using SSH
- [x] Configure passwordless ssh login to pi
- [x] Install Home Assistant Supervisor
- [x] Install Portainer for container management
- [x] Install pi hole as a container `docker-compose up -d`

xref: [Docs to setup pi os](https://community.home-assistant.io/t/installing-home-assistant-supervised-on-raspberry-pi-os/201836)

**Comment by rkumar2468** [comment]
Had some hiccups with flashing the OS onto the SD card. 
D:\ drive wasnt recognized as a file system after flashing it using balenaEtcher.

**Comment by rkumar2468** [comment]
Validations were failing, so just ignored it and continued.
ssh on to pi using putty
user pass : pi/raspberry

**Comment by rkumar2468** [comment]
```
sudo -i
apt-get install -y software-properties-common apparmor-utils apt-transport-https ca-certificates curl dbus jq network-manager
systemctl disable ModemManager
systemctl stop ModemManager
curl -fsSL get.docker.com | sh
curl -sL "https://raw.githubusercontent.com/Kanga-Who/home-assistant/master/supervised-installer.sh" | bash -s -- -m raspberrypi3
```

**Comment by rkumar2468** [comment]
Reason for installing supervised, as core on containers does not support supervisor. And it has limitations without supervisor on HASS.

xref: https://www.home-assistant.io/installation/#compare-installation-methods

**Comment by rkumar2468** [comment]
Installing HA using the below cmds instead of the `supervised-installer`, as its been outdated and not working.
```
 rm -f /etc/docker/daemon.json
wget https://github.com/home-assistant/os-agent/releases/download/1.2.2/os-agent_1.2.2_linux_armv7.deb
dpkg -i os-agent_1.2.2_linux_armv7.deb

wget https://github.com/home-assistant/supervised-installer/releases/latest/download/homeassistant-supervised.deb
dpkg -i homeassistant-supervised.deb
```

xref: https://github.com/home-assistant/supervised-installer#installation

**Comment by rkumar2468** [comment]
Configure passwordless ssh login to pi
Run the below cmds on your machine to setup passwordless logins using putty or ssh
```
ssh-keygen # Generates OPENSSH pub/private key pairs, hit just enter for a paraphrase field for passwordless experience
# Copy the public key to the server or remote pi
cat ~/.ssh/id_rsa.pub | ssh pi@<remote_host_id> "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"

# Testing
ssh pi@<remote_host_id>
```

Putty SSH passwordless login
- Unfortunately putty cannot recognize openssh id_rsa private key, so we need to convert it to ppk format.
- Open puttygen, load pri key from the previously generated id_rsa key 
- Save the private as .ppk format
- Update the Putty -> SSH -> Auth Private key section to use the saved .ppk file
xref: [References for how to use the private key for Putty SSH authentication](https://devops.ionos.com/tutorials/use-ssh-keys-with-putty-on-windows/)

**Comment by rkumar2468** [comment]
## Installing Portainer for container management
```
sudo docker pull portainer/portainer-ce:latest
sudo docker run -d -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
```
Or you may use this [docker-compose.yaml](https://github.com/rkumar2468/canakit/blob/main/docker/docker-compose.yaml) and [run this script](https://github.com/rkumar2468/canakit/blob/main/scripts/setup-portainer-and-pihole.sh) to install portainer and pihole. As a prerequisite [install docker-compose using the below comment](https://github.com/rkumar2468/canakit/issues/1#issuecomment-1045438015)

**Comment by rkumar2468** [comment]
Install docker-compose on pi
```
# Replace with the latest version from https://github.com/docker/compose/releases/latest
DOCKER_COMPOSE_VERSION="2.2.3"
# For 32-bit OS use:
DOCKER_COMPOSE_ARCH="armv7"

sudo curl -L "https://github.com/docker/compose/releases/download/v${DOCKER_COMPOSE_VERSION}/docker-compose-linux-${DOCKER_COMPOSE_ARCH}" -o /usr/bin/docker-compose
sudo chmod +x /usr/bin/docker-compose
```

**Comment by rajrku** [comment]
https://firebog.net/ is a fantastic spot to get all the adlists.
1. Goto [this page in pihole](http://rasberrypi/admin/groups-adlists.php) and update the URLs from ☝  lists.
2. After updating the URLs, update gravity/database [records using this page](http://rasberrypi/admin/gravity.php)
